[project]
name = "ckanext-umss"
version = "0.0.1"
description = "Plataforma de Datos Abiertos UMSS"
readme = "README.md"
authors = [
    {name = "Daniel BLC", email = "daniel@umss.edu.bo"}
]
license = {text = "AGPL"}
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

keywords = [ "CKAN", "datos", "abiertos", "umss", ]
dependencies = []

[project.urls]
Homepage = "https://github.com/umss/ckanext-umss"

[project.entry-points."ckan.plugins"]
umss = "ckanext.umss.plugin:UmssPlugin"


[build-system]
requires = ["setuptools<82"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
        "ignore::sqlalchemy.exc.SADeprecationWarning",
        "ignore::sqlalchemy.exc.SAWarning",
        "ignore::DeprecationWarning",
]
addopts = "--ckan-ini test.ini"
